# Generated by Django 5.2.1 on 2025-05-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(default='unknown', max_length=10),
        ),
    ]
