# Generated by Django 5.2.1 on 2025-06-22 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('mention', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='main.event')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month', to='main.month')),
            ],
        ),
        migrations.CreateModel(
            name='LookCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recommend', models.TextField()),
                ('is_avoid', models.TextField()),
                ('avoid_reason', models.TextField()),
                ('emoticon', models.ImageField(blank=True, null=True, upload_to='emoticons/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookcards', to='main.event')),
                ('event_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_month', to='main.eventmonth')),
            ],
        ),
        migrations.CreateModel(
            name='LookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('상의', '상의'), ('하의', '하의'), ('악세서리', '악세서리')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('look_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.lookcard')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.ManyToManyField(to='main.month'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment_images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('look_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.lookcard')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='main.tag')),
            ],
        ),
    ]
