# Generated by Django 5.2.1 on 2025-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='LookCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LookId', models.IntegerField()),
                ('Lookname', models.CharField(max_length=8)),
                ('LookImg', models.ImageField(upload_to='post/')),
                ('LookEXP', models.TextField()),
                ('Look_MaxTemp', models.FloatField()),
                ('Look_MinTemp', models.FloatField()),
                ('likes', models.IntegerField()),
                ('tags', models.ManyToManyField(related_name='LookTags', to='main.tag')),
            ],
        ),
    ]
