# Generated by Django 5.2.1 on 2025-06-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lookcard',
        ),
    ]
