# Generated by Django 5.2.1 on 2025-06-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.ManyToManyField(blank=True, related_name='month', to='main.month'),
        ),
        migrations.AlterField(
            model_name='lookitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
