# Generated by Django 5.2.1 on 2025-06-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookcard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lookcard',
            name='emoticon',
        ),
        migrations.AddField(
            model_name='event',
            name='emoticon',
            field=models.ImageField(blank=True, null=True, upload_to='emoticons/'),
        ),
    ]
