# Generated by Django 5.2.1 on 2025-06-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_event_month_alter_lookitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookcard',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookcards', to='main.month'),
        ),
    ]
