# Generated by Django 5.2.3 on 2025-06-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_count',
        ),
    ]
