# Generated by Django 5.2.1 on 2025-05-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(blank=True, null=True)),
                ('rain', models.IntegerField(blank=True, null=True)),
                ('sunshine', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
