# Generated by Django 5.2.1 on 2025-05-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdb',
            name='sunshine',
        ),
        migrations.RemoveField(
            model_name='weatherdb',
            name='temp',
        ),
        migrations.AddField(
            model_name='weatherdb',
            name='temp_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdb',
            name='temp_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdb',
            name='wind_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdb',
            name='rain',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
