# Generated by Django 5.2.1 on 2025-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0002_remove_weatherdb_sunshine_remove_weatherdb_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdb',
            name='stn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
